spring:

  application:
    name: 'task-me'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'none'
    properties:
      hibernate:
        type: trace

  datasource:
    url: jdbc:mysql://localhost:3308/task4?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  liquibase:
    enabled: true
    change-log: 'classpath:/migrations/db.changelog-master.xml'
    url: jdbc:mysql://localhost:3308/task4?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    user: root
    password: root



server:
  port: 8888

#LOGGING
logging:
  level:
    root: info

#SECURITY
jwt:
  secret: secret_key
  expiration: 999999999
  authorizationHeader: Auth
